[build]
  publish = "output"
  command = "PYTHONPATH=$PYTHONPATH:. python -m pelican content -o output -s publishconf.py && echo '/* /index.html 200' > output/_redirects"

[build.environment]
  PYTHON_VERSION = "3.11"

[context.production]
  command = "PYTHONPATH=$PYTHONPATH:. python -m pelican content -o output -s publishconf.py && echo '/* /index.html 200' > output/_redirects"

[context.deploy-preview]
  command = "PYTHONPATH=$PYTHONPATH:. python -m pelican content -o output -s publishconf.py && echo '/* /index.html 200' > output/_redirects"

[context.branch-deploy]
  command = "PYTHONPATH=$PYTHONPATH:. python -m pelican content -o output -s publishconf.py && echo '/* /index.html 200' > output/_redirects"

