[build]
  publish = "output"
  command = "pip install -r requirements.txt && make publish"

[build.environment]
  PYTHON_VERSION = "3.11"

[context.production]
  command = "pip install -r requirements.txt && make publish"

[context.deploy-preview]
  command = "pip install -r requirements.txt && make publish"

[context.branch-deploy]
  command = "pip install -r requirements.txt && make publish"

