[build]
  publish = "output"
  command = "python -m pelican content -o output -s publishconf.py"

[build.environment]
  PYTHON_VERSION = "3.11"

# Force HTTPS for all requests
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# Custom domain settings
[context.production]
  environment = { SITEURL = "https://hub.twinko.ai" }

# Redirect netlify.app to custom domain
[[redirects]]
  from = "https://twinkohub.netlify.app/*"
  to = "https://hub.twinko.ai/:splat"
  status = 301
  force = true

# Redirect for SPA behavior (only if needed)
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

