[build]
  command = """
    echo "Building Twinko Hub..."
    pelican content -s publishconf.py
    echo "✅ English site built."
    pelican content -s publishconf_zh.py
    echo "✅ Chinese site built."
    echo "✅ Build completed."
  """
  publish = "output"

[build.environment]
  PYTHON_VERSION = "3.11"

# Force HTTPS for all requests
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# Custom domain settings
[context.production]
  environment = { SITEURL = "https://hub.twinko.ai", PELICAN_ENV = "production" }

[context.deploy-preview]
  environment = { PELICAN_ENV = "preview" }

[context.branch-deploy]
  environment = { PELICAN_ENV = "staging" }

# Redirect from Netlify subdomain to your custom domain (optional)
[[redirects]]
  from = "https://twinkohub.netlify.app/*"
  to = "https://hub.twinko.ai/:splat"
  status = 301
  force = true

# Ensure blog posts work
[[redirects]]
  from = "/blog/*"
  to = "/blog/:splat/index.html"
  status = 200
  force = false

# Ensure newsletter articles work
[[redirects]]
  from = "/newsletter/*"
  to = "/newsletter/:splat/index.html"
  status = 200
  force = false

# Ensure Chinese blog posts work
[[redirects]]
  from = "/zh/blog/*"
  to = "/zh/blog/:splat/index.html"
  status = 200
  force = false

# Ensure Chinese newsletter articles work
[[redirects]]
  from = "/zh/newsletter/*"
  to = "/zh/newsletter/:splat/index.html"
  status = 200
  force = false

# Handle 404s for HTML pages by redirecting to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

# Add a custom 404 page
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Redirect for SPA behavior (only if needed)
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

