[build]
  publish = "output"
  command = "python -m pelican content -o output -s publishconf.py"

[build.environment]
  PYTHON_VERSION = "3.11"
  PYTHONPATH = "."  # Set PYTHONPATH here

# Context-specific commands removed as they are identical to the main build command.
# Netlify will inherit the command from [build] for production, deploy-preview, and branch-deploy.

# Redirect rule for Single Page Application (SPA) behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

