[build]
  command = "chmod +x build.sh && ./build.sh"
  publish = "output"

[build.environment]
  PYTHON_VERSION = "3.11"
  PYTHONPATH = "."

[context.production]
  command = "chmod +x build.sh && ./build.sh"

[context.deploy-preview]
  command = "chmod +x build.sh && ./build.sh"

[context.branch-deploy]
  command = "chmod +x build.sh && ./build.sh" 